### ISSUE TITLE
Implement Universal Viewer or Leaflet Viewer

### ISSUE THREAD

**Issue by netsensei** [VlaamseKunstcollectie/Arthub-Frontend#32]
Currently, we use [Project Mirador](http://projectmirador.org/
) as our viewer. This was our "go to" option since we integrated images on short notice. We still need to research alternative viewers and pick a viewer which is best suitable for our purposes.

Other contenders are [Universal Viewer](https://universalviewer.io/) and [Leaflet](https://github.com/mejackreed/Leaflet-IIIF).

**Comment by Hobbesball** [comment]
this is being done as part of the imagehub project. Closing here :+1:
