### ISSUE TITLE
ignore publish-image flag

### ISSUE THREAD

**Issue by Hobbesball** [VlaamseKunstcollectie/Arthub-Frontend#41]
currently a series of if statements checks if an image is probably in the public domain or not, and thus if a thumbnail and image should be shown on the arthub or not. For our 200 test images rights have been cleared and the publish-image flag can be ignored. This will result in all images being shown irrespective of the copyright status of that image. 

The actual policy around this will be put in place in a next phase of the imagehub project.

**Comment by Kitania** [comment]
Changed in 2a371e513451b8e4a75e88b11554111dd646c9c2
